Include YTP2CCP.
tomodachi94/awesome-computercraft pull request #16
Opened 2022-11-17 19:31 UTC by TheAio

Add YTP2CCP under the fun catagory.

- [Y ] I have read the [contribution guidelines](./CONTRIBUTING.md).
- [ Y] I agree to release my contributions under the [CC-BY-SA](./LICENSE.md) license.
- [ ] I have read the automated feedback from the spell-checker after submitting this pull request. 

## Summary of changes

Add YTP2CCP with pastebin link under "fun" catagory.

2022-11-17 20:58 UTC, tomodachi94 requested changes
This looks really good except for one minor thing.

2022-11-17 20:58 UTC, tomodachi94 commented on README.md
> +- YTP2CCP: Convert commented YouTube piano notes and play them in CC:T. **[pastebin](https://pastebin.com/nxEMWHY3)**
```suggestion
- YTP2CCP: Convert commented YouTube piano notes and play them in CC:T. **[Pastebin](https://pastebin.com/nxEMWHY3)**
```

2022-11-18 18:24 UTC, tomodachi94 approved these changes

2022-11-18 18:24 UTC, merged

2022-12-16 04:47 UTC, tomodachi94 commented
@TheAio minor question, is this available on GitHub or something? I have a few minor improvements I'd like to make.

2022-12-16 08:41 UTC, TheAio commented
@tomodachi94 unfortunately not. But you are welcome to copy the code and modify it or just make a repo out of it, however please leave the first line as some kind of credit.