Add Tampl and pixelbox_lite and pngLua and Acidity and Gemu
tomodachi94/awesome-computercraft pull request #20
Opened 2023-06-27 11:49 UTC by 9551-Dev

- [ya] I have read the [contribution guidelines](./CONTRIBUTING.md).
- [ya] I agree to release my contributions under the [CC-BY-SA](./LICENSE.md) license.
- [ ] I have read the automated feedback from the spell-checker after submitting this pull request. 

## Summary of changes

Add Tampl and pixelbox_lite and pngLua and Acidity and Gemu

2023-06-28 18:47 UTC, tomodachi94 requested changes
Thanks for contributing. Please correct the changes I've pointed out above. Please then run the awesome-lint linter per the contributing guidelines. (Feel free to ignore the spellchecker, I'm in the process of replacing it with a better one that allows linting things like this.)

(Lurkers: Feel free to point out any issues with this PR, I'm on mobile so I won't be as thorough as I would on a laptop.)

2023-06-28 18:47 UTC, tomodachi94 commented on README.md
> +- [GEMU](https://github.com/9551-Dev/GEMU) -  CraftOS pc graphics mode emulator based on pixelbox
```suggestion
- [GEMU](https://github.com/9551-Dev/GEMU) -  CraftOS-PC graphics mode emulator based on Pixelbox.
```

2023-06-28 18:47 UTC, tomodachi94 commented on README.md
> +- [Acidity](https://github.com/9551-Dev/acidity) -  A simple to use [procedual world generation](https://cdn.discordapp.com/attachments/477911902152949771/1078015614712565770/image.png) oriented nois
```suggestion
- [Acidity](https://github.com/9551-Dev/acidity) -  A simple [procedual world generation](https://cdn.discordapp.com/attachments/477911902152949771/1078015614712565770/image.png)-oriented noise generation library.
```

2023-06-28 18:47 UTC, tomodachi94 commented on README.md
> +- [PngLua](https://github.com/9551-Dev/pngLua) -  Png image parsing library designed for computercraft
```suggestion
- [PngLua](https://github.com/9551-Dev/pngLua) -  PNG parsing library designed for ComputerCraft.
```

2023-06-28 18:47 UTC, tomodachi94 commented on README.md
> +- [Pixelbox lite](https://github.com/9551-Dev/apis/blob/main/pixelbox_lite.lua) - An insanely fast [drawing character](https://cdn.discordapp.com/attachments/876936991256743947/1123213991813058751/im
```suggestion
- [Pixelbox Lite](https://github.com/9551-Dev/apis/blob/main/pixelbox_lite.lua) - An insanely fast [drawing character](https://cdn.discordapp.com/attachments/876936991256743947/1123213991813058751/image.png) processing library.
```

2023-06-28 18:47 UTC, tomodachi94 commented on README.md
> +- [Tampl](https://github.com/9551-Dev/tampl) -  Lua tokenization/parsing library designed for injecting code into existing programs and dynamic code generation
```suggestion
- [Tampl](https://github.com/9551-Dev/tampl) - A Lua tokenization and parsing library designed for dynamic code generation and injecting code into existing programs.
```

2023-06-29 07:51 UTC, 9551-Dev commented
man im sorry for leaving so many mistakes lol but i coulnt figure out how to modify a PR with git lmao

2023-06-29 07:53 UTC, 9551-Dev commented
honestly not sure what awesome-link is complaining about now?

2023-06-29 14:53 UTC, tomodachi94 commented
@9551-Dev me neither, I've been meaning to replace it with something *much* better. I'm going to merge this in with a squash.

Thank you for your contribution!

(P.S. you can amend a commit by running `git commit --amend`.)

2023-06-29 14:53 UTC, merged